base_url: !secret base_url
small_window: "/ngsi-ld/v1/entities/urn:ngsi-ld:Pharma_smaller_time_window:001"
large_window: "/ngsi-ld/v1/entities/urn:ngsi-ld:Pharma_greater_time_window:001"
wp3_alarms: "/ngsi-ld/v1/entities/urn:ngsi-ld:Pharma_alarms:001"
output_entity: "/ngsi-ld/v1/entities/urn:ngsi-ld:Pharma_solution_output_1:001"



solution_1:
  inputs: ["DataIngestion_OCT_probePositionEvaluation", "DataIngestion_OCT_probePosition_xPos", "DataIngestion_OCT_probePosition_yPos"]
  lower_thresholds: [0.5, 400, 50]
  upper_thresholds: [null, 900, 200]
  alarm_type : "OCT Position Deviation"
  kafka_topic: "pharma_alerts-solution1"

solution_2:
  inputs_1: ["DataIngestion_OCT_signalQualityCheck_maxSignalIntensity"]

  inputs_2: ["DataIngestion_OCT_signalQualityCheck_numBadImg"]
  upper_thresholds_2: ["DataIngestion_OCT_imageClassification_numGoodImg"]
  pct_change_2 : [10]

solution_3:
  inputs: ["DataIngestion_OCT_signalQualityCheck_maxSignalIntensity"]

solution_4:
  inputs: ["DataIngestion_OCT_signalQualityCheck_maxSignalIntensity"]

