# Dagster libraries to run both dagster-webserver and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.11-slim-bullseye

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/dagster_service

RUN mkdir -p $DAGSTER_HOME

COPY src/dagster_service/workspace.yaml $DAGSTER_HOME
COPY src/dagster_service* $DAGSTER_HOME

RUN pip install -r $DAGSTER_HOME/requirements.txt
RUN pip install -e $DAGSTER_HOME

WORKDIR $DAGSTER_HOME