pharma:
  notification:
    url: "http://0.0.0.0:8000/pharma"
    attrs: ["attribute1", "attribute2"]
    metadata: ["dateCreated", "dateModified"]

  entity: "EntityType"
  orion_endpoint: "http://orion_host:port/v2/subscriptions"
  kafka_topic: "pharma"

  dag_config:
    base_url: "http://0.0.0.0:2016/ngsi-ld/v1/entities/"
    small_window: "urn:ngsi-ld:Pharma_smaller_time_window:001"
    large_window: "urn:ngsi-ld:Pharma_greater_time_window:001"
    wp3_alarms: "urn:ngsi-ld:Pharma_alarms:001"
    output_entity: "urn:ngsi-ld:Pharma_solution_output_1:001"

    solution_1:
      inputs: [ "DataIngestion_OCT_probePositionEvaluation", "DataIngestion_OCT_probePosition_xPos", "DataIngestion_OCT_probePosition_yPos" ]
      lower_thresholds: [ 0.5, 400.0, 50.0 ]
      upper_thresholds: [ 999.9, 900.0, 200.0 ]
      alarm_type: "OCT Position Deviation"
      kafka_topic: "pharma_alerts-solution1"

    solution_2:
      inputs_1: [ "DataIngestion_OCT_signalQualityCheck_maxSignalIntensity" ]
      inputs_2: [ "DataIngestion_OCT_imageClassification_numBadImg" ]
      upper_thresholds_2: [ "DataIngestion_OCT_imageClassification_numGoodImg" ]
      pct_change_2: [ 10 ]
      alarm_type_1: "Poor Signal Quality"
      alarm_type_2: "Bad Image increase"
      kafka_topic: "pharma_alerts-solution2"

    solution_3:
      inputs: [ "Pharma_DataIngestion_IR_numberOfValues", "Pharma_DataIngestion_IR_plsModelReliability", "Pharma_DataIngestion_IR_frequency"]
      kafka_topic: "pharma_alerts-solution3"

    solution_4:
      inputs: [ "Pharma_DataIngestion_PWR_numberOfValues", "Pharma_DataIngestion_PWR_frequency"]
      kafka_topic: "pharma_alerts-solution4"

    solution_5:
      inputs_1: ["Pharma_RuntimeAIProcessing_Prediction_timeframe", "Pharma_RuntimeAIProcessing_Prediction_timestep",
      "Pharma_RuntimeAIProcessing_Prediction_status" ]
      inputs_2: ["RuntimeAIProcessing_Prediction_MSE"]
      upper_thresholds_2: ["RuntimeAIProcessing_Prediction_MSE_Target"]
      kafka_topic: "pharma_alerts-solution5"



