name: Build and Push Docker Image

on:
  push:
    branches:
      - Dag01

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Dagster Service
        uses: docker/build-push-action@v4
        with:
          push: true
          file: src/dagster_service/Dockerfile_dagster
          tags: ghcr.io/eng_autonomic_manager/dagster_service:latest

      - name: Build and push Orion Catcher
        uses: docker/build-push-action@v4
        with:
          context: src
          push: true
          file: src/Dockerfile
          tags: ghcr.io/eng_autonomic_manager/orion_catcher:latest
